al-mi-pio/alpimi-planner-backend

API/Configuration/AuthConfiguration.cs, API/Configuration/RequiredCharacterTypes.cs, API/Context.cs, API/DbService.cs, API/Entities/User/Commands/CreateUserCommand.cs, API/Entities/User/UserController.cs, API/Utilities/Configuration.cs, Unit/Entities/User/Commands/CreateUserCommand.unit.cs, Unit/Entities/User/Commands/DeleteUserCommand.unit.cs
Dodano zasady dla hasła
zasada dla unikatowego loginu będzie dodana w tasku w którym będzie dodany GetUserBYLogin
=> 33 dodaj zasady do createuser

API/Configuration/AuthConfiguration.cs, API/Entities/Auth/Auth.cs, API/Entities/Auth/Queries/LoginQuery.cs, API/Entities/User/Commands/CreateUserCommand.cs, API/Entities/User/UserController.cs, API/Utilities/Configuration.cs, Migrations/20241019221131_SaltedAuth.Designer.cs, Migrations/20241019221131_SaltedAuth.cs, README.md, Unit/Entities/Auth/Queries/LoginQuery.unit.cs, Unit/Entities/User/Commands/CreateUserCommand.unit.cs, Unit/Entities/User/Commands/UpdateUserCommand.unit.cs, Unit/Entities/User/Queries/GetUserByLoginQuery.unit.cs, Unit/Entities/User/Queries/GetUserQuery.unit.cs
=> Fix GitHub repository history

API/AdminInit.cs, API/Entities/EAuth/Queries/LoginQuery.cs, API/Entities/EUser/Commands/CreateUserCommand.cs, API/Entities/EUser/Commands/UpdateUserCommand.cs, API/Entities/EUser/Queries/GetUserByLoginQuery.cs, API/Entities/EUser/Queries/GetUserQuery.cs, API/Entities/EUser/UserController.cs, API/Program.cs, API/Utilities/Privileges.cs, Test/Entities/EUser/Commands/CreateUserCommand.unit.cs, Test/Entities/EUser/Commands/UpdateUserCommand.unit.cs, Test/Entities/EUser/Queries/GetUserByLoginQuery.unit.cs, Test/Entities/EUser/Queries/GetUserQuery.unit.cs
Używaj null do handlerów by nie filtrować po UserID
=> 51 rework priveleges

API/AdminInit.cs, API/Context.cs, API/DbService.cs, API/Entities/EAuth/Queries/LoginQuery.cs, API/Entities/EUser/Commands/CreateUserCommand.cs, API/Entities/EUser/Commands/UpdateUserCommand.cs, API/Entities/EUser/Queries/GetUserByLoginQuery.cs, API/Entities/EUser/Queries/GetUserQuery.cs, API/Entities/EUser/UserController.cs, Test/Entities/EUser/Commands/UpdateUserCommand.unit.cs, Test/Entities/EUser/Queries/GetUserByLoginQuery.unit.cs, Test/Entities/EUser/Queries/GetUserQuery.unit.cs
=> 55 rework filtra

API/Entities/EAuth/AuthController.cs, API/Entities/EUser/UserController.cs, API/Program.cs, alpimi-planner-backend.csproj
=> 39 upiksz swaggera wedug alberta

API/Context.cs, API/DbService.cs, API/Entities/EAuth/AuthController.cs, API/Entities/ESchedule/Commands/CreateScheduleCommand.cs, API/Entities/ESchedule/Commands/DeleteScheduleCommand.cs, API/Entities/ESchedule/Commands/UpdateScheduleCommand.cs, API/Entities/ESchedule/DTO/CreateScheduleDTO.cs, API/Entities/ESchedule/DTO/UpdateScheduleDTO.cs, API/Entities/ESchedule/Queries/GetScheduleByLoginQuery.cs, API/Entities/ESchedule/Queries/GetScheduleQuery.cs, API/Entities/ESchedule/Queries/GetSchedulesQuery.cs, API/Entities/ESchedule/Schedule.cs, API/Entities/ESchedule/ScheduleController.cs, API/Entities/EUser/Commands/UpdateUserCommand.cs, API/Entities/EUser/Queries/GetUserByLoginQuery.cs, API/Entities/EUser/Queries/GetUserQuery.cs, API/Entities/EUser/UserController.cs, API/IDbService.cs, Migrations/20241024221321_AddedSchedule.Designer.cs, Migrations/20241024221321_AddedSchedule.cs
=> 18 dodaj entity schedule

API/Entities/EAuth/AuthController.cs, API/Entities/ESchedule/Queries/GetSchedulesQuery.cs, API/Entities/ESchedule/ScheduleController.cs, API/Entities/EUser/UserController.cs, API/Responses/ApiGetAllResponse.cs, API/Responses/ApiGetResponse.cs, API/Responses/Pagination.cs, API/Responses/PaginationParams.cs, API/Settings/AuthSettings.cs, API/Settings/PaginationSettings.cs, Test/Entities/ESchedule/Queries/GetSchedulesQuery.cs
Errory zostaną zrobione w następnym mergu
=> 60 ujednolici struktur odpowiedzi api

API/Entities/EAuth/AuthController.cs, API/Entities/EAuth/Queries/LoginQuery.cs, API/Entities/EAuth/Queries/RefreshTokenQuery.cs, API/Responses/PaginationParams.cs, API/Settings/AuthSettings.cs, API/Utilities/Configuration.cs, API/Utilities/Privileges.cs, Test/Entities/EAuth/Queries/RefreshTokenQuery.unit.cs
Login ma brata
Robienie refresh tokena
było bolesne 
nwm czy tak wolno
=> 71 dodaj endpoint refreshtoken

API/Entities/EAuth/AuthController.cs, API/Entities/EAuth/Queries/LoginQuery.cs, API/Entities/ESchedule/Commands/CreateScheduleCommand.cs, API/Entities/ESchedule/Commands/UpdateScheduleCommand.cs, API/Entities/ESchedule/Queries/GetSchedulesQuery.cs, API/Entities/ESchedule/ScheduleController.cs, API/Entities/EUser/Commands/CreateUserCommand.cs, API/Entities/EUser/Commands/UpdateUserCommand.cs, API/Entities/EUser/UserController.cs, API/Program.cs, API/Responses/ApiErrorResponse.cs, Test/Entities/EAuth/Queries/LoginQuery.unit.cs, Test/Entities/ESchedule/Commands/CreateScheduleCommand.unit.cs, Test/Entities/ESchedule/Commands/UpdateScheduleCommand.unit.cs, Test/Entities/ESchedule/Queries/GetSchedulesQuery.cs, Test/Entities/EUser/Commands/CreateUserCommand.unit.cs, Test/Entities/EUser/Commands/UpdateUserCommand.unit.cs
Errory śmigają bez żadnych błędów
=> 70 ujednolici struktur errorw

API/AdminInit.cs, API/Entities/EAuth/AuthController.cs, API/Entities/EAuth/Queries/LoginQuery.cs, API/Entities/ESchedule/Commands/CreateScheduleCommand.cs, API/Entities/ESchedule/Commands/UpdateScheduleCommand.cs, API/Entities/ESchedule/ScheduleController.cs, API/Entities/EUser/Commands/CreateUserCommand.cs, API/Entities/EUser/Commands/UpdateUserCommand.cs, API/Entities/EUser/UserController.cs, API/Locales/Errors.cs, API/Locales/Errors.pl-PL.resx, API/Locales/Errors.resx, API/Locales/General.cs, API/Locales/General.pl-PL.resx, API/Locales/General.resx, API/Program.cs, Test/Entities/EAuth/Queries/LoginQuery.unit.cs, Test/Entities/ESchedule/Commands/CreateScheduleCommand.unit.cs, Test/Entities/ESchedule/Commands/UpdateScheduleCommand.unit.cs, Test/Entities/EUser/Commands/CreateUserCommand.unit.cs, Test/Entities/EUser/Commands/UpdateUserCommand.unit.cs, Test/TestUtilities/ResourceSetup.cs
Po wielu mękach się udało
jeśli testy nie działają to nie moja wina
=> 67 dodaj locales

README.md
Jak w tytule, przy okazji poprawiłem dużo rzeczy które mnie irytowały w tym readme 😎
=> Dodaj sekcję "Test setup" w readme #79

API/Entities/EAuth/AuthController.cs, API/Entities/ESchedule/ScheduleController.cs, API/Entities/EUser/UserController.cs, API/Program.cs, API/Settings/AuthSettings.cs, API/Settings/RateLimiterSettings.cs, Test/Entities/EAuth/AuthController.test.cs, Test/Entities/ESchedule/ScheduleController.test.cs, Test/Entities/EUser/UserController.test.cs
z tym cackiem nikt nas nie zddosuje
=> 77 dodaj ochron przed ddosem

API/Entities/EDayOff/Commands/CreateDayOffCommand.cs, API/Entities/EDayOff/Queries/GetAllDayOffBySchedule.cs, API/Entities/ESchedule/Queries/GetAllSchedulesQuery.cs, Test/Entities/EDayOff/Queries/GetAllDayOffBySchedule.unit.cs, Test/Entities/ESchedule/Queries/GetAllSchedulesQuery.unit.cs
=> 89 napraw get all pagnation error

API/Database/Context.cs, API/Entities/EStudent/Commands/CreateStudentCommand.cs, API/Entities/EStudent/DTO/CreateStudentDTO.cs, API/Entities/EStudent/Queries/GetAllStudentsQuery.cs, API/Entities/EStudent/StudentController.cs, API/Entities/EStudentSubgroup/Commands/CreateStudentSubgroupCommand.cs, API/Entities/EStudentSubgroup/Commands/DeleteStudentSubgroupCommand.cs, API/Entities/EStudentSubgroup/DTO/CreateStudentSubgroupDTO.cs, API/Entities/EStudentSubgroup/StudentSubgroup.cs, API/Entities/EStudentSubgroup/StudentSubgroupController.cs, API/Entities/ESubgroup/Commands/DeleteSubgroupCommand.cs, API/Entities/ESubgroup/Queries/GetAllSubgroups.cs, API/Entities/ESubgroup/SubgroupController.cs, API/Locales/Errors.pl-PL.resx, API/Locales/Errors.resx, Migrations/20241129142219_AddedStudentSubgroup.Designer.cs, Migrations/20241129142219_AddedStudentSubgroup.cs, Test/Entities/EStudent/StudentController.test.cs, Test/Entities/ESubgroup/Queries/GetAllSubgroupsByGroupQuery.unit.cs, Test/Entities/ESubgroup/SubgroupController.test.cs
Poźniej dodam unit testy i integrity testy
=> 13 dodaj entity studentgroup

API/Database/Context.cs, API/Entities/EClassroom/Classroom.cs, API/Entities/EClassroom/ClassroomController.cs, API/Entities/EClassroom/Commands/CreateClassroomCommand.cs, API/Entities/EClassroom/Commands/DeleteClassroomCommand.cs, API/Entities/EClassroom/Commands/UpdateClassroomCommand.cs, API/Entities/EClassroom/DTO/CreateClassroomDTO.cs, API/Entities/EClassroom/DTO/UpdateClassroomDTO.cs, API/Entities/EClassroom/Queries/GetAllClassrooms.cs, API/Entities/EClassroom/Queries/GetClassroomQuery.cs, API/Entities/EClassroomType/Commands/CreateClassroomTypeCommand.cs, API/Entities/EClassroomType/Commands/UpdateClassroomTypeCommand.cs, API/Entities/EClassroomType/Queries/GetAllClassroomTypesQuery.cs, API/Entities/EClassroomType/Queries/GetClassroomTypeQuery.cs, Migrations/20241204210633_AddedClassroom.Designer.cs, Migrations/20241204210633_AddedClassroom.cs, Test/Entities/EClassroom/ClassroomController.test.cs, Test/Entities/EClassroom/Commands/CreateClassromCommand.unit.cs, Test/Entities/EClassroom/Commands/UpdateCLassroomCommand.unit.cs, Test/Entities/EClassroom/Queries/GetAllClassroomsQuery.unit.cs, Test/Entities/EClassroomType/Commands/CreateClassroomTypeCommand.unit.cs, Test/Plan/Classroom.md, Test/Setup/DbHelper.cs, Test/TestUtilities/MockData.cs
Działa tak jak działać powinno
mamy sale G120
i możemy hartować w E5
=> 16 dodaj entity classroom

API/Database/Context.cs, API/Entities/EClassroom/ClassroomController.cs, API/Entities/EClassroom/Commands/CreateClassroomCommand.cs, API/Entities/EClassroom/Commands/UpdateClassroomCommand.cs, API/Entities/EClassroom/DTO/CreateClassroomDTO.cs, API/Entities/EClassroom/DTO/UpdateClassroomDTO.cs, API/Entities/EClassroom/Queries/GetAllClassroomsQuery.cs, API/Entities/EClassroomType/ClassroomTypeController.cs, API/Entities/EClassroomType/Commands/DeleteClassroomTypeCommand.cs, API/Entities/EClassroomType/Queries/GetAllClassroomTypesQuery.cs, API/Entities/EStudent/Commands/UpdateStudentCommand.cs, API/Relations/ClassroomClassroomType.cs, Migrations/20241209213330_AddedClassroomClassroomType.Designer.cs, Migrations/20241209213330_AddedClassroomClassroomType.cs, Test/Entities/EClassroom/ClassroomController.test.cs, Test/Entities/EClassroom/Commands/CreateClassromCommand.unit.cs, Test/Entities/EClassroom/Commands/UpdateCLassroomCommand.unit.cs, Test/Entities/EClassroomType/ClassroomTypeController.test.cs, Test/Plan/Classroom.md, Test/Plan/ClassroomType.md, Test/Plan/Student.md
wrzeczie sala G120 może być salą komputerową :O
=> 107 dodaj relacje classroomtype classroom

API/Database/Context.cs, API/Entities/EClassroomType/ClassroomTypeController.cs, API/Entities/EClassroomType/Commands/DeleteClassroomTypeCommand.cs, API/Entities/EClassroomType/Queries/GetAllClassroomTypesQuery.cs, API/Entities/ELesson/Commands/CreateLessonCommand.cs, API/Entities/ELesson/Commands/UpdateLessonCommand.cs, API/Entities/ELesson/DTO/CreateLessonDTO.cs, API/Entities/ELesson/DTO/UpdateLessonDTO.cs, API/Relations/LessonClassroomType.cs, Migrations/20241210175350_AddedLessonClassroomType.Designer.cs, Migrations/20241210175350_AddedLessonClassroomType.cs, Test/Entities/EClassroomType/ClassroomTypeController.test.cs, Test/Entities/ELesson/Commands/CreateLessonCommand.unit.cs, Test/Entities/ELesson/Commands/UpdateLessonCommand.unit.cs, Test/Entities/ELesson/LessonController.test.cs, Test/Plan/ClassroomType.md, Test/Plan/Lesson.md
Teraz bazie danych mogą wreszcie wymagać komputerów
=> 108 dodaj relacje classroomtype   lesson

API/Database/Context.cs, API/Entities/ELesson/Commands/UpdateLessonCommand.cs, API/Entities/ELesson/DTO/LessonDTO.cs, API/Entities/ELesson/Queries/GetAllLessonsQuery.cs, API/Entities/ELessonBlock/Commands/CreateLessonBlockCommand.cs, API/Entities/ELessonBlock/Commands/DeleteLessonBlockCommand.cs, API/Entities/ELessonBlock/Commands/UpdateLessonBlockCommand.cs, API/Entities/ELessonBlock/DTO/CreateLessonBlockDTO.cs, API/Entities/ELessonBlock/DTO/LessonBlockDTO.cs, API/Entities/ELessonBlock/DTO/UpdateLessonBlockDTO.cs, API/Entities/ELessonBlock/LessonBlock.cs, API/Entities/ELessonBlock/LessonBlockController.cs, API/Entities/ELessonBlock/Queries/GetAllLessonBlocksQuery.cs, API/Entities/ELessonBlock/Queries/GetLessonBlockQuery.cs, API/Entities/EScheduleSettings/Commands/UpdateScheduleSettingsCommand.cs, API/Locales/Errors.pl-PL.resx, API/Locales/Errors.resx, API/Utilities/DataTrimmer.cs, Migrations/20241214195348_AddedLessonBlock.Designer.cs, Migrations/20241214195348_AddedLessonBlock.cs, Test/Entities/EScheduleSettings/Commands/UpdateScheduleSettingsCommand.unit.cs, Test/Entities/EScheduleSettings/ScheduleSettingsController.test.cs, Test/Setup/ResourceSetup.cs
czy działa pewnie tak sprawdza w WIELKIM testowaniu
ale dużo roboty z tym było
testy dostanie w przyszłości
=> 126 dodaj entity lessonblock v2

API/Entities/ELesson/Commands/CreateLessonCommand.cs, API/Entities/ELesson/Commands/UpdateLessonCommand.cs, API/Entities/ELessonType/Commands/CreateLessonTypeCommand.cs, API/Entities/ELessonType/Commands/UpdateLessonTypeCommand.cs, API/Entities/ESchedule/Commands/CreateScheduleCommand.cs, API/Entities/EScheduleSettings/Commands/UpdateScheduleSettingsCommand.cs, Test/Entities/ELesson/Commands/CreateLessonCommand.unit.cs, Test/Entities/ELesson/Commands/UpdateLessonCommand.unit.cs, Test/Entities/ELessonType/Commands/CreateLessonTypeCommand.unit.cs, Test/Entities/ELessonType/Commands/UpdateLessonTypeCommand.unit.cs, Test/Entities/ESchedule/Commands/CreateScheduleCommand.unit.cs, Test/Entities/EScheduleSettings/Commands/UpdateScheduleSettingsCommand.unit.cs, Test/Plan/LessonType.md, Test/Plan/Schedule.md, Test/Plan/ScheduleSettings.md
Pierwszy jeździec WIELKIEGO oczyszczenia 
jeden z wielu
=> 131 wielkie sprzatanie ostatnie funkcje

API/Entities/EClassroom/ClassroomController.cs, API/Entities/EClassroomType/ClassroomTypeController.cs, API/Entities/EDayOff/DayOffController.cs, API/Entities/EGroup/GroupController.cs, API/Entities/ELesson/LessonController.cs, API/Entities/ELessonBlock/LessonBlockController.cs, API/Entities/ELessonPeriod/LessonPeriodController.cs, API/Entities/ELessonType/LessonTypeController.cs, API/Entities/ESchedule/ScheduleController.cs, API/Entities/EStudent/StudentController.cs, API/Entities/ESubgroup/SubgroupController.cs, API/Entities/ETeacher/TeacherController.cs, API/Program.cs, API/Settings/RateLimiterSettings.cs, API/Utilities/Configuration.cs, Test/Entities/EAuth/AuthController.test.cs, Test/Entities/EClassroom/ClassroomController.test.cs, Test/Entities/EClassroomType/ClassroomTypeController.test.cs, Test/Entities/EDayOff/DayOffController.test.cs, Test/Entities/EGroup/GroupController.test.cs, Test/Entities/ELesson/LessonController.test.cs, Test/Entities/ELessonBlock/LessonBlockController.test.cs, Test/Entities/ELessonPeriod/LessonPeriodController.test.cs, Test/Entities/ELessonType/LessonTypeController.test.cs, Test/Entities/ESchedule/ScheduleController.test.cs, Test/Entities/EScheduleSettings/ScheduleSettingsController.test.cs, Test/Entities/EStudent/StudentController.test.cs, Test/Entities/ESubgroup/SubgroupController.test.cs, Test/Entities/ETeacher/TeacherController.test.cs, Test/Entities/EUser/UserController.test.cs
Drugi jeździec WIELKIEGO oczyszczenia
kolejny z wielu
zwiastun jedności
=> 133 wielkie sprzatanie configuracja
